eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: "guest"
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
      
logstash:
  host: localhost
  port: 5000

timezone: EST
